test:
  image: python:3.10
  stage: test
  artifacts:
    paths:
      - public
  script:
    - pip install -r requirements.txt
    - pytest --cov-report html:public --cov

pages:
  only:
    - master
  stage: deploy
  script:
    - echo "🚀 Deploying coverage report."
  artifacts:
    paths:
      - public
