repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(paddle/static/css/.*\.min\.css|paddle/static/js/.*\.min\.js)$
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.6
  #   hooks:
  #     - id: bandit
  #       args: ["-r", "."]
