# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(kanoe/static/css/.*\.min\.css|kanoe/static/js/.*\.min\.js)$
      - id: check-yaml
      - id: check-added-large-files
