"""empty message

Revision ID: 0dc044ac3c23
Revises: c8cd8ff9c99e
Create Date: 2024-02-13 16:18:15.911102

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0dc044ac3c23"
down_revision = "c8cd8ff9c99e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "race_number",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("min_number_id", sa.Integer(), nullable=True),
        sa.Column("max_number_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["min_number_id"],
            ["number.id"],
        ),
        sa.ForeignKeyConstraint(
            ["max_number_id"],
            ["number.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["race.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "category_id", name="uq_race_category"),
    )
    op.add_column("paddler", sa.Column("gender", sa.String(length=1), nullable=True))
    op.create_foreign_key(
        None, "paddler", "membership_body", ["membership_body_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "paddler", type_="foreignkey")
    op.drop_column("paddler", "gender")
    op.drop_table("number_race")
    # ### end Alembic commands ###
