"""empty message

Revision ID: 56711208cd56
Revises: e3e94e9034a1
Create Date: 2023-09-23 06:11:01.532524

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56711208cd56"
down_revision = "e3e94e9034a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership_body",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("acronym", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "paddler", sa.Column("membership_body_id", sa.Integer(), nullable=True)
    )
    # op.create_foreign_key(None, 'paddler', 'membership_body', ['membership_body_id'], ['id'])
    op.alter_column("paddler", "bcu", new_column_name="membership_number")
    op.alter_column("paddler", "bcu_expiry", new_column_name="membership_expiry")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("paddler", "membership_expiry", new_column_name="bcu_expiry")
    op.alter_column("paddler", "membership_number", new_column_name="bcu")
    op.drop_column("paddler", "membership_body_id")
    op.drop_table("membership_body")
    # ### end Alembic commands ###
