"""empty message

Revision ID: 68cf0f59baf7
Revises: 0dc044ac3c23
Create Date: 2024-02-26 06:43:36.390460

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68cf0f59baf7"
down_revision = "0dc044ac3c23"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_paddler",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("paddler_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paddler_id"],
            ["paddler.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_paddler_paddler_id"), "team_paddler", ["paddler_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_paddler_team_id"), "team_paddler", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_paddler_team_id"), table_name="team_paddler")
    op.drop_index(op.f("ix_team_paddler_paddler_id"), table_name="team_paddler")
    op.drop_table("team_paddler")
    # ### end Alembic commands ###
