"""empty message

Revision ID: 75f5fe4bb22d
Revises: 68cf0f59baf7
Create Date: 2024-02-26 13:15:57.972100

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75f5fe4bb22d"
down_revision = "68cf0f59baf7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK_crew_team_4", "crew", type_="foreignkey")
    op.drop_column("crew", "team_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crew", sa.Column("team_id", sa.INTEGER(), nullable=True))
    op.create_foreign_key("FK_crew_team_4", "crew", "team", ["team_id"], ["id"])
    # ### end Alembic commands ###
