"""empty message

Revision ID: c8cd8ff9c99e
Revises: 56711208cd56
Create Date: 2023-09-23 06:34:04.203403

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8cd8ff9c99e"
down_revision = "56711208cd56"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
