"""Race default time adjustment

Revision ID: e3e94e9034a1
Revises: 915a89d96e8b
Create Date: 2023-03-12 07:54:26.853460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3e94e9034a1"
down_revision = "915a89d96e8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("race", sa.Column("time_adjustment", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("race", "time_adjustment")
    # ### end Alembic commands ###
