--liquibase formatted sql
--changeset datawookie:915a89d96e8b
--precondition-sql-check expectedResult:1 SELECT COUNT(*) FROM alembic_version WHERE version_num = 'c84b26c56825'
--comment Running upgrade f58b19f13496 -> 915a89d96e8b

INSERT INTO club (code_regex, name) VALUES ('4AS', 'Newark 4 As');
INSERT INTO club (code_regex, name) VALUES ('ABF', 'Aberfan');
INSERT INTO club (code_regex, name, services) VALUES ('ACU', 'Army Canoe Union', 1);
INSERT INTO club (code_regex, name) VALUES ('ADS', 'Addlestone');
INSERT INTO club (code_regex, name) VALUES ('ANK', 'Anker Valley');
INSERT INTO club (code_regex, name) VALUES ('AVN', 'Avon');
INSERT INTO club (code_regex, name) VALUES ('BAD', 'Barking & Dagenham');
INSERT INTO club (code_regex, name) VALUES ('BAN', 'Banbury & District');
INSERT INTO club (code_regex, name) VALUES ('BAS|BCC', 'Basingstoke Canal');
INSERT INTO club (code_regex, name) VALUES ('BED', 'Bedford School');
INSERT INTO club (code_regex, name) VALUES ('BEJ', 'Bourne End Junior');
INSERT INTO club (code_regex, name) VALUES ('BOA', 'Bradford On Avon');
INSERT INTO club (code_regex, name) VALUES ('BPR', 'Burton Phoenix Racers');
INSERT INTO club (code_regex, name) VALUES ('BPS', 'Broadland Paddle Sport');
INSERT INTO club (code_regex, name) VALUES ('BRE', 'Brecon');
INSERT INTO club (code_regex, name) VALUES ('BRI', 'Bristol');
INSERT INTO club (code_regex, name) VALUES ('BRK', 'Break Out');
INSERT INTO club (code_regex, name) VALUES ('BRY', 'Bryanston School');
INSERT INTO club (code_regex, name) VALUES ('BSF', 'Bishops Stortford');
INSERT INTO club (code_regex, name) VALUES ('BTH', 'Bath');
INSERT INTO club (code_regex, name) VALUES ('BUR', 'Burton');
INSERT INTO club (code_regex, name) VALUES ('CAM', 'Cambridge');
INSERT INTO club (code_regex, name) VALUES ('CDF', 'Cardiff Bay Kayakers');
INSERT INTO club (code_regex, name) VALUES ('CEL', 'Celbridge');
INSERT INTO club (code_regex, name) VALUES ('CHE', 'Chester');
INSERT INTO club (code_regex, name) VALUES ('CHU', 'Churcher''s College');
INSERT INTO club (code_regex, name) VALUES ('CKP|COK', 'Cokethorpe School');
INSERT INTO club (code_regex, name) VALUES ('CLM', 'Chelmsford');
INSERT INTO club (code_regex, name) VALUES ('CNI', 'Canoe Northern Ireland');
INSERT INTO club (code_regex, name) VALUES ('CRA', 'Cranleigh School');
INSERT INTO club (code_regex, name) VALUES ('DAU', 'Dauntsey''s School');
INSERT INTO club (code_regex, name) VALUES ('DCP', 'Dyffryn Conwy');
INSERT INTO club (code_regex, name) VALUES ('DEV', 'Devizes');
INSERT INTO club (code_regex, name) VALUES ('DUD', 'Duddon');
INSERT INTO club (code_regex, name) VALUES ('DWR', 'Cardiff');
INSERT INTO club (code_regex, name) VALUES ('EAL', 'Ealing');
INSERT INTO club (code_regex, name) VALUES ('ELM', 'Elmbridge');
INSERT INTO club (code_regex, name, services) VALUES ('ENG', 'Royal Engineers', 1);
INSERT INTO club (code_regex, name) VALUES ('ERN', 'Erne Paddlers');
INSERT INTO club (code_regex, name) VALUES ('ESK', 'Edinburgh Schools Kayak');
INSERT INTO club (code_regex, name) VALUES ('EXE', 'Exeter');
INSERT INTO club (code_regex, name) VALUES ('FLA', 'Fladbury');
INSERT INTO club (code_regex, name) VALUES ('FOR', 'Forth');
INSERT INTO club (code_regex, name) VALUES ('FOX', 'Falcon (Oxford)');
INSERT INTO club (code_regex, name) VALUES ('FOY', 'Fowey River');
INSERT INTO club (code_regex, name) VALUES ('GAI', 'Gailey');
INSERT INTO club (code_regex, name) VALUES ('GLO', 'Gloucester');
INSERT INTO club (code_regex, name) VALUES ('GLS', 'Glanford & Scunthorpe');
INSERT INTO club (code_regex, name) VALUES ('GLW', 'Glasgow');
INSERT INTO club (code_regex, name) VALUES ('HAS', 'Hastings & District');
INSERT INTO club (code_regex, name) VALUES ('HEM', 'Hemel Hempstead');
INSERT INTO club (code_regex, name) VALUES ('HEN', 'Henley');
INSERT INTO club (code_regex, name) VALUES ('HER', 'Hereford');
INSERT INTO club (code_regex, name) VALUES ('HUN', 'Huntingdon');
INSERT INTO club (code_regex, name) VALUES ('HYM', 'Herts Young Mariners Base');
INSERT INTO club (code_regex, name) VALUES ('ICH', 'Ichthus');
INSERT INTO club (code_regex, name) VALUES ('IND', 'Independent');
INSERT INTO club (code_regex, name) VALUES ('IPS', 'Ipswich');
INSERT INTO club (code_regex, name) VALUES ('KCC', 'Kilcullen');
INSERT INTO club (code_regex, name) VALUES ('KEL', 'Kelly College');
INSERT INTO club (code_regex, name) VALUES ('KIM', 'Kimbolton School');
INSERT INTO club (code_regex, name) VALUES ('KIN', 'Kingston (Hull)');
INSERT INTO club (code_regex, name) VALUES ('KIR', 'Kirkcaldy');
INSERT INTO club (code_regex, name) VALUES ('LAK', 'Lakeland');
INSERT INTO club (code_regex, name) VALUES ('LAU', 'Launceston College');
INSERT INTO club (code_regex, name) VALUES ('LBZ', 'Leighton Buzzard');
INSERT INTO club (code_regex, name) VALUES ('LDN', 'London Tideway');
INSERT INTO club (code_regex, name) VALUES ('LEA', 'Leaside');
INSERT INTO club (code_regex, name) VALUES ('LEE', 'Lee Valley');
INSERT INTO club (code_regex, name) VALUES ('LIN', 'Lincoln');
INSERT INTO club (code_regex, name) VALUES ('LKR', 'Linlithgow');
INSERT INTO club (code_regex, name) VALUES ('LON', 'Longridge');
INSERT INTO club (code_regex, name) VALUES ('LOR|LWC', 'Lord Wandsworth College');
INSERT INTO club (code_regex, name) VALUES ('LOU', 'Loughborough University');
INSERT INTO club (code_regex, name) VALUES ('MAD', 'Macclesfield & District');
INSERT INTO club (code_regex, name) VALUES ('MAI', 'Maidstone');
INSERT INTO club (code_regex, name) VALUES ('MAL', 'Malton & Norton');
INSERT INTO club (code_regex, name) VALUES ('MAR', 'Marlborough College');
INSERT INTO club (code_regex, name) VALUES ('MDN', 'Meridian');
INSERT INTO club (code_regex, name) VALUES ('MER', 'Mercia');
INSERT INTO club (code_regex, name) VALUES ('MKS', 'Mount Kelly School');
INSERT INTO club (code_regex, name) VALUES ('MLO', 'Marlow');
INSERT INTO club (code_regex, name) VALUES ('MVR', 'Manvers Waterfront');
INSERT INTO club (code_regex, name) VALUES ('NAI', 'Nairn');
INSERT INTO club (code_regex, name) VALUES ('NBY|NEW', 'Newbury');
INSERT INTO club (code_regex, name) VALUES ('NMC', 'North Merchiston');
INSERT INTO club (code_regex, name) VALUES ('NOR', 'Norwich');
INSERT INTO club (code_regex, name) VALUES ('NOT', 'Nottingham');
INSERT INTO club (code_regex, name) VALUES ('NSK', 'North East Sea Kayak');
INSERT INTO club (code_regex, name) VALUES ('OSC', 'Ocean Sports Club');
INSERT INTO club (code_regex, name) VALUES ('OXU|UOX', 'Oxford University');
INSERT INTO club (code_regex, name) VALUES ('PAN', 'Pangbourne');
INSERT INTO club (code_regex, name) VALUES ('PEN', 'Pennine');
INSERT INTO club (code_regex, name) VALUES ('PLY', 'Plymouth College');
INSERT INTO club (code_regex, name) VALUES ('PNZ', 'Penzance');
INSERT INTO club (code_regex, name) VALUES ('POO', 'Poole Harbour');
INSERT INTO club (code_regex, name) VALUES ('PPL', 'Paddleplus');
INSERT INTO club (code_regex, name) VALUES ('PRA', 'Paddlesport Racers');
INSERT INTO club (code_regex, name) VALUES ('PUT', 'Putney Bridge');
INSERT INTO club (code_regex, name, services) VALUES ('RAF', 'Royal Air Force', 1);
INSERT INTO club (code_regex, name) VALUES ('RDG|REA', 'Reading');
INSERT INTO club (code_regex, name) VALUES ('RHS', 'Royal Hosp School');
INSERT INTO club (code_regex, name) VALUES ('RIC', 'Richmond');
INSERT INTO club (code_regex, name) VALUES ('RLS', 'Royal Leamington Spa');
INSERT INTO club (code_regex, name, services) VALUES ('RMC|RMK', 'Royal Marines', 1);
INSERT INTO club (code_regex, name, services) VALUES ('RNP', 'Royal Navy', 1);
INSERT INTO club (code_regex, name) VALUES ('ROY', 'Royal');
INSERT INTO club (code_regex, name) VALUES ('RUN', 'Runcorn');
INSERT INTO club (code_regex, name) VALUES ('SER', 'Seren');
INSERT INTO club (code_regex, name) VALUES ('SHK', 'The Sharks');
INSERT INTO club (code_regex, name) VALUES ('SHP', 'Shropshire');
INSERT INTO club (code_regex, name) VALUES ('SKR', 'Strathclyde');
INSERT INTO club (code_regex, name) VALUES ('SLP', 'Salmon Leap');
INSERT INTO club (code_regex, name) VALUES ('SOL', 'Solihull');
INSERT INTO club (code_regex, name) VALUES ('SOR', 'Soar Valley');
INSERT INTO club (code_regex, name) VALUES ('SOU', 'Southampton');
INSERT INTO club (code_regex, name) VALUES ('SOW', 'Special Olympic Wales');
INSERT INTO club (code_regex, name) VALUES ('SPS', 'Scottish Performance Squad');
INSERT INTO club (code_regex, name) VALUES ('STO', 'Stoke Racers');
INSERT INTO club (code_regex, name) VALUES ('SUT', 'Sutton Bingham & District');
INSERT INTO club (code_regex, name) VALUES ('SWA', 'Swansea');
INSERT INTO club (code_regex, name) VALUES ('SWY', 'Stornoway');
INSERT INTO club (code_regex, name) VALUES ('TAM', 'Tamar Valley Nomads');
INSERT INTO club (code_regex, name) VALUES ('TAU', 'Taunton');
INSERT INTO club (code_regex, name) VALUES ('TON', 'Tonbridge');
INSERT INTO club (code_regex, name) VALUES ('TRE', 'Trentham');
INSERT INTO club (code_regex, name) VALUES ('TRU', 'Truro');
INSERT INTO club (code_regex, name) VALUES ('TTN', 'Thomastown Paddlers');
INSERT INTO club (code_regex, name, services) VALUES ('UKF', 'United Kingdom Armed Forces', 1);
INSERT INTO club (code_regex, name) VALUES ('VIK', 'Viking');
INSERT INTO club (code_regex, name) VALUES ('WCP', 'West Coast Paddlers');
INSERT INTO club (code_regex, name) VALUES ('WCR', 'Winchester & District');
INSERT INTO club (code_regex, name) VALUES ('WEY', 'Wey');
INSERT INTO club (code_regex, name) VALUES ('WIN', 'Winchester');
INSERT INTO club (code_regex, name) VALUES ('WOK', 'Wokingham');
INSERT INTO club (code_regex, name) VALUES ('WOL', 'Wolverhampton');
INSERT INTO club (code_regex, name) VALUES ('WOP', 'Wear Whoppers');
INSERT INTO club (code_regex, name) VALUES ('WOR', 'Worcester');
INSERT INTO club (code_regex, name) VALUES ('WRC', 'White Rose (Leeds)');
INSERT INTO club (code_regex, name) VALUES ('WYC', 'Wiltshire Youth');

UPDATE alembic_version SET version_num='915a89d96e8b' WHERE alembic_version.version_num = 'c84b26c56825';
