from .age_group import *
from .announcement import *
from .base import *
from .category import *
from .club import *
from .crew import *
from .entry import *
from .member import *
from .number import *
from .paddler import *
from .race import *
from .result import *
from .series import *
from .team import *
from .trial import *
from .user import *
